trigger: 
- main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: install node

  - script: |
      npm install
      npm run build
      npm _suite
    displayName: npm install and build

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/ResultsFile*.xml'